<?php
//wasrvdb数据库配置
$glb_mysql_server_ip="221.174.50.145";
$glb_mysql_server_port=3306;
$glb_mysql_username="hpclouduser";
$glb_mysql_password="hpcloud";
$glb_mysql_database="wasrvdb";
$glb_mysql_sock="/mysql/3306/mysql.sock";

define('HOST_DB', "wahostdb");//单个网站流量和搜索统计数据库
define('SITES_DB', "wasitesdb");//网站分类排名数据库
define('WORD_DB', "waworddb");//keywords数据库
define('UID_DB', "wauiddb");//keywords数据库
define('SRV_DB', "wasrvdb");//服务数据库

?>
