<?php
define("TRANSFER_DATE_TYPE","time_type");
define("TRANSFER_DATE_VALUE","time_value");
define("TRANSFER_OPERATION","operation");
define("DAY_QUERY",1);
define("TOP_DOMAIN_QUERY",2);
define("TOP_HOST_QUERY",3);
define("TOP_URL_QUERY",4);
define("TOP_UID_QUERY",5);
define("TOP_UPSTREAM_QUERY",6);
define("TOP_DOWNSTREAM_QUERY",7);
define("TOP_KEYWORD_QUERY",8);

define("TOP_HOSTSW_QUERY",20);
define("TOP_HOSTSE_QUERY",21);
define("TOP_SWHOST_QUERY",22);

define("TOP_MAJORCATES_QUERY",30);
define("TOP_SUBCATES_QUERY",31);
define("TOP_DOMAINS_QUERY",32);
define("TOP_HOSTS_QUERY",33);
define("TOP_WORDS_QUERY",34);

define("TOP_ENGINE_QUERY",40);
define("TOP_SW_QUERY",41);

define("TRANSFER_RESULT",'results');
define("TRANSFER_RESULTROWS",'rows');

define("OPERATE_OK",97);//操作成功
define("OPERATE_ERROR",98);//操作失败
define("SERVER_ERROR",99);//服务器错误
define("ARGU_INVALID",120);//参数不合法

//keyword相关常量开始
define("TRANSFER_KEYWORD","word");
//keyword相关常量结束

//userID相关常量开始
define("TRANSFER_USERID","uid");
define("TOP_KEYWORD_QUERY",5);
//userID相关常量结束

//webcate相关常量开始
define("MAJOR_CATEGORY","major_cate");
define("SUB_CATEGORY","sub_cate");
define("TRANSFER_WEBCATE","cate");
define("TRANSFER_WEBCATE_TYPE","websitecate_type");
define("TRANSFER_WEBCATE_VALUE","websitecate_value");
//webcate相关常量结束

?>
